config/routes.rb
Coast2coast::Application.routes.draw do
  
  resources :team_of_the_weeks

  root "static_pages#home"
  get "sp/spdata"
  get "saves/savedata"
  get "gaa/gaadata"
  get "wins/winsdata"
  get "blocks/blocksdata"
  get "ppp/pppdata"
  get "hits/hitdata"
  get "pim/pimdata"
  get "plus_minus/pmdata"
  get "assists/assistsdata"
  get "goals/goalsdata"
  

  resources :weeks

end

app/models/week.rb
class Week < ActiveRecord::Base
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: [:show, :edit, :update, :destroy]

  # GET /weeks
  # GET /weeks.json
  def index
    @weeks = Week.all
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
  end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit
  end

  # POST /weeks
  # POST /weeks.json
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        format.html { redirect_to @week, notice: 'Week was successfully created.' }
        format.json { render action: 'show', status: :created, location: @week }
      else
        format.html { render action: 'new' }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeks/1
  # PATCH/PUT /weeks/1.json
  def update
    respond_to do |format|
      if @week.update(week_params)
        format.html { redirect_to @week, notice: 'Week was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.json
  def destroy
    @week.destroy
    respond_to do |format|
      format.html { redirect_to weeks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def week_params
      params.require(:week).permit(:week_number, :team, :goals, :assists, :plus_minus, :ppp, :hits, :blocks, :wins, :gaa, :saves, :save_p)
    end
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.erb
<%= form_for(@week) do |f| %>
  <% if @week.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
      <% @week.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :week_number %><br>
    <%= f.number_field :week_number %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :goals %><br>
    <%= f.number_field :goals %>
  </div>
  <div class="field">
    <%= f.label :assists %><br>
    <%= f.number_field :assists %>
  </div>
  <div class="field">
    <%= f.label :plus_minus %><br>
    <%= f.number_field :plus_minus %>
  </div>
  <div class="field">
    <%= f.label :ppp %><br>
    <%= f.number_field :ppp %>
  </div>
  <div class="field">
    <%= f.label :hits %><br>
    <%= f.number_field :hits %>
  </div>
  <div class="field">
    <%= f.label :blocks %><br>
    <%= f.number_field :blocks %>
  </div>
  <div class="field">
    <%= f.label :wins %><br>
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :gaa %><br>
    <%= f.text_field :gaa %>
  </div>
  <div class="field">
    <%= f.label :saves %><br>
    <%= f.number_field :saves %>
  </div>
  <div class="field">
    <%= f.label :save_p %><br>
    <%= f.text_field :save_p %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weeks/edit.html.erb
<h1>Editing week</h1>

<%= render 'form' %>

<%= link_to 'Show', @week %> |
<%= link_to 'Back', weeks_path %>

app/views/weeks/index.html.erb
<h1>Listing weeks</h1>

<table>
  <thead>
    <tr>
      <th>Week number</th>
      <th>Team</th>
      <th>Goals</th>
      <th>Assists</th>
      <th>Plus minus</th>
      <th>Ppp</th>
      <th>Hits</th>
      <th>Blocks</th>
      <th>Wins</th>
      <th>Gaa</th>
      <th>Saves</th>
      <th>Save p</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weeks.each do |week| %>
      <tr>
        <td><%= week.week_number %></td>
        <td><%= week.team %></td>
        <td><%= week.goals %></td>
        <td><%= week.assists %></td>
        <td><%= week.plus_minus %></td>
        <td><%= week.ppp %></td>
        <td><%= week.hits %></td>
        <td><%= week.blocks %></td>
        <td><%= week.wins %></td>
        <td><%= week.gaa %></td>
        <td><%= week.saves %></td>
        <td><%= week.save_p %></td>
        <td><%= link_to 'Show', week %></td>
        <td><%= link_to 'Edit', edit_week_path(week) %></td>
        <td><%= link_to 'Destroy', week, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Week', new_week_path %>

app/views/weeks/new.html.erb
<h1>New week</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week number:</strong>
  <%= @week.week_number %>
</p>

<p>
  <strong>Team:</strong>
  <%= @week.team %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @week.goals %>
</p>

<p>
  <strong>Assists:</strong>
  <%= @week.assists %>
</p>

<p>
  <strong>Plus minus:</strong>
  <%= @week.plus_minus %>
</p>

<p>
  <strong>Ppp:</strong>
  <%= @week.ppp %>
</p>

<p>
  <strong>Hits:</strong>
  <%= @week.hits %>
</p>

<p>
  <strong>Blocks:</strong>
  <%= @week.blocks %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @week.wins %>
</p>

<p>
  <strong>Gaa:</strong>
  <%= @week.gaa %>
</p>

<p>
  <strong>Saves:</strong>
  <%= @week.saves %>
</p>

<p>
  <strong>Save p:</strong>
  <%= @week.save_p %>
</p>

<%= link_to 'Edit', edit_week_path(@week) %> |
<%= link_to 'Back', weeks_path %>