config/routes.rb
Coast2coast::Application.routes.draw do
  
  resources :team_of_the_weeks

  root "static_pages#home"
  get "sp/spdata"
  get "saves/savedata"
  get "gaa/gaadata"
  get "wins/winsdata"
  get "blocks/blocksdata"
  get "ppp/pppdata"
  get "hits/hitdata"
  get "pim/pimdata"
  get "plus_minus/pmdata"
  get "assists/assistsdata"
  get "goals/goalsdata"
  

  resources :weeks

end

app/models/team_of_the_week.rb
class TeamOfTheWeek < ActiveRecord::Base
end

app/controllers/team_of_the_weeks_controller.rb
class TeamOfTheWeeksController < ApplicationController
  before_action :set_team_of_the_week, only: [:show, :edit, :update, :destroy]

  # GET /team_of_the_weeks
  # GET /team_of_the_weeks.json
  def index
    @team_of_the_weeks = TeamOfTheWeek.all
  end

  # GET /team_of_the_weeks/1
  # GET /team_of_the_weeks/1.json
  def show
    @team_of_the_week = TeamOfTheWeek.find(params[:id])
  end

  # GET /team_of_the_weeks/new
  def new
    @team_of_the_week = TeamOfTheWeek.new
  end

  # GET /team_of_the_weeks/1/edit
  def edit
  end

  # POST /team_of_the_weeks
  # POST /team_of_the_weeks.json
  def create
    @team_of_the_week = TeamOfTheWeek.new(team_of_the_week_params)

    respond_to do |format|
      if @team_of_the_week.save
        format.html { redirect_to @team_of_the_week, notice: 'Team of the week was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team_of_the_week }
      else
        format.html { render action: 'new' }
        format.json { render json: @team_of_the_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_of_the_weeks/1
  # PATCH/PUT /team_of_the_weeks/1.json
  def update
    respond_to do |format|
      if @team_of_the_week.update(team_of_the_week_params)
        format.html { redirect_to @team_of_the_week, notice: 'Team of the week was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team_of_the_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_of_the_weeks/1
  # DELETE /team_of_the_weeks/1.json
  def destroy
    @team_of_the_week.destroy
    respond_to do |format|
      format.html { redirect_to team_of_the_weeks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_of_the_week
      @team_of_the_week = TeamOfTheWeek.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_of_the_week_params
      params[:team_of_the_week]
    end
end

app/helpers/team_of_the_weeks_helper.rb
module TeamOfTheWeeksHelper
end

app/views/team_of_the_weeks/_form.html.haml
= form_for @team_of_the_week do |f|
  - if @team_of_the_week.errors.any?
    #error_explanation
      %h2= "#{pluralize(@team_of_the_week.errors.count, "error")} prohibited this team_of_the_week from being saved:"
      %ul
        - @team_of_the_week.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/team_of_the_weeks/edit.html.haml
%h1 Editing team_of_the_week

= render 'form'

= link_to 'Show', @team_of_the_week
\|
= link_to 'Back', team_of_the_weeks_path

app/views/team_of_the_weeks/index.html.haml
.row
  .large-8.columns.center
    %h1 Listing team_of_the_weeks

/ First Band (Slider)
.row
  .large-12.columns
    #slider{"data-orbit" => ""}
      %img{src: "http://placehold.it/1000x400&text=[ img 1 ]"}/
      %img{src: "http://placehold.it/1000x400&text=[ img 2 ]"}/
      %img{src: "http://placehold.it/1000x400&text=[ img 3 ]"}/
    %hr/
/ Three-up Content Blocks
.row
  .large-4.columns
    %img{src: "http://placehold.it/400x300&text=[img]"}/
    %h4 This is a content section.
    %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
  .large-4.columns
    %img{src: "http://placehold.it/400x300&text=[img]"}/
    %h4 This is a content section.
    %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
  .large-4.columns
    %img{src: "http://placehold.it/400x300&text=[img]"}/
    %h4 This is a content section.
    %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
/ Call to Action Panel
.row
  .large-12.columns
    .panel
      %h4 Get in touch!
      .row
        .large-9.columns
          %p We'd love to hear from you, you attractive person you.
        .large-3.columns
          %a.radius.button.right{href: "#"} Contact Us


/ - @team_of_the_weeks.each do |team_of_the_week|
/ %tr
/   %td= link_to 'Show', team_of_the_week
/   %td= link_to 'Edit', edit_team_of_the_week_path(team_of_the_week)
/   %td= link_to 'Destroy', team_of_the_week, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br
/ = link_to 'New Team of the week', new_team_of_the_week_path


%script{src: "../assets/js/jquery.js"}
%script{src: "../assets/js/templates/foundation.js"}
:javascript
  $(document).foundation();

  var doc = document.documentElement;
  doc.setAttribute('data-useragent', navigator.userAgent);

app/views/team_of_the_weeks/new.html.haml
%h1 New team_of_the_week

= render 'form'

= link_to 'Back', team_of_the_weeks_path

app/views/team_of_the_weeks/show.html.haml
%p#notice= notice

.center 
  %h2 Team of the week for week #{(@team_of_the_week.week.to_i + 1)}

.center-50
  %h3 Skater Categories
%table.center-75
  %thead
    %tr
      %th
        Goals
      %th
        Assists
      %th
        Plus Minus
      %th
        PIMS
      %th
        PPP
      %th
        Hits
      %th
        Blocks
    %tr
      %td
        =@team_of_the_week.goalteam
      %td
        =@team_of_the_week.assistteam
      %td
        =@team_of_the_week.plus_minusteam
      %td
        =@team_of_the_week.pimteam
      %td
        =@team_of_the_week.pppteam
      %td
        =@team_of_the_week.hitteam
      %td
        =@team_of_the_week.blockteam
.center-50
  %h3 Goalie Categories
%table.center-50
  %thead
    %tr
      %th
        Wins
      %th
        Goals Against Average
      %th
        Saves
      %th
        Save Percentage
    %tr
      %td
        =@team_of_the_week.winteam
      %td
        =@team_of_the_week.gaateam
      %td
        =@team_of_the_week.saveteam
      %td
        =@team_of_the_week.save_pteam
.row
  .large-4.columns
    First Star
  .large-4.columns
    Second Star
  .large-4.columns
    Third Star  




= link_to 'Edit', edit_team_of_the_week_path(@team_of_the_week)
\|
= link_to 'Back', team_of_the_weeks_path